/**
 * Demo market observations — DETERMINISTIC synthetic series for development.
 *
 * Generated by a seeded PRNG (not random per load), always isMock=true, and
 * always shown behind a demo banner. Real observations replace these as soon
 * as a real market data source is connected (see store.ts).
 */
import type { CommodityId, MarketObservation } from '../../types/market';
import { COMMODITY_IDS } from './commodities.ts';

/** Mulberry32 seeded PRNG — deterministic across loads. */
function prng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const BASE_PRICE: Record<CommodityId, number> = {
  ibirayi: 480,
  ibishyimbo: 820,
  ibigori: 360,
  inyanya: 620,
  igitoki: 260,
  umuceri: 1050,
  imyumbati: 320,
};

const SPOTS: Array<{ market: string; district: string }> = [
  { market: 'Kimironko', district: 'Gasabo' },
  { market: 'Nyabugogo', district: 'Nyarugenge' },
  { market: 'Musanze', district: 'Musanze' },
];

function buildSeries(): MarketObservation[] {
  const out: MarketObservation[] = [];
  const now = Date.now();
  const DAY = 24 * 3600_000;
  COMMODITY_IDS.forEach((commodity, ci) => {
    const rand = prng(1000 + ci * 77);
    SPOTS.forEach((spot, si) => {
      const jitter = prng(5000 + ci * 131 + si * 17);
      let price = (BASE_PRICE[commodity] ?? 500) * (1 + (jitter() - 0.5) * 0.12);
      for (let d = 59; d >= 0; d--) {
        const drift = (rand() - 0.5) * 0.035;
        // Gentle documented demo seasonality: dips near "harvest" days.
        const seasonal = 1 - 0.06 * Math.max(0, Math.sin((d / 60) * Math.PI * 2 + ci));
        price = Math.max(50, price * (1 + drift) * (0.995 + 0.01 * seasonal));
        const observedAt = new Date(now - d * DAY - si * 3600_000).toISOString();
        out.push({
          id: `demo-m-${commodity}-${si}-${d}`,
          commodity,
          price: Math.round(price),
          currency: 'RWF',
          unit: 'kg',
          pricePerKg: Math.round(price),
          market: spot.market,
          district: spot.district,
          source: {
            name: 'Ibihe Demo',
            url: 'https://ibihe.rw/isoko',
            publishedAt: observedAt,
            fetchedAt: observedAt,
            language: 'rw',
          },
          observedAt,
          fetchedAt: observedAt,
          isMock: true,
        });
      }
    });
  });
  return out;
}

export const DEMO_OBSERVATIONS: MarketObservation[] = buildSeries();
